services:
 - type: web
   name: whatsapp-bot
   runtime: docker
   repo: https://github.com/AstroX11/whatsapp-bot
   plan: free
   envVars:
    - key: USER_NUMBER
      sync: false
    - key: OWNER_NAME
      sync: false
    - key: BOT_NAME
      sync: false
   region: oregon
   dockerContext: .
   dockerfilePath: ./Dockerfile
version: "1"
