import {
	fact,
	getAdvice,
	getAffirmation,
	getCatFact,
	getDogFact,
	getInsult,
	getJoke,
	getKanyeQuote,
	getNumberFact,
	getQuote,
	getRizz,
} from "../../client/Utils";
import type { CommandModule } from "../../client/Core";

export default [
	{
		pattern: "rizz",
		desc: "Rizz your babe lol",
		type: "fun",
		fromMe: false,
		isGroup: false,
		run: async msg => msg.send(await getRizz()),
	},
	{
		pattern: "insult",
		desc: "Insult one",
		type: "fun",
		fromMe: false,
		isGroup: false,
		run: async msg => msg.send(await getInsult()),
	},
	{
		pattern: "joke",
		desc: "Get a random joke",
		type: "fun",
		fromMe: false,
		isGroup: false,
		run: async msg => msg.send(await getJoke()),
	},
	{
		pattern: "advice",
		desc: "Get a random piece of advice",
		type: "fun",
		fromMe: false,
		isGroup: false,
		run: async msg => msg.send(await getAdvice()),
	},
	{
		pattern: "fact",
		desc: "Get a random fact",
		type: "fun",
		fromMe: false,
		isGroup: false,
		run: async msg => msg.send(await fact()),
	},
	{
		pattern: "quote",
		desc: "Get an inspirational quote",
		type: "fun",
		fromMe: false,
		isGroup: false,
		run: async msg => msg.send(await getQuote()),
	},
	{
		pattern: "catfact",
		desc: "Get a random cat fact",
		type: "fun",
		fromMe: false,
		isGroup: false,
		run: async msg => msg.send(await getCatFact()),
	},
	{
		pattern: "dogfact",
		desc: "Get a random dog fact",
		type: "fun",
		fromMe: false,
		isGroup: false,
		run: async msg => msg.send(await getDogFact()),
	},
	{
		pattern: "number",
		desc: "Get a random number fact",
		type: "fun",
		fromMe: false,
		isGroup: false,
		run: async msg => msg.send(await getNumberFact()),
	},
	{
		pattern: "affirmation",
		desc: "Get a positive affirmation",
		type: "fun",
		fromMe: false,
		isGroup: false,
		run: async msg => msg.send(await getAffirmation()),
	},
	{
		pattern: "kanye",
		desc: "Get a Kanye West quote",
		type: "fun",
		fromMe: false,
		isGroup: false,
		run: async msg => msg.send(await getKanyeQuote()),
	},
] satisfies CommandModule[];
