export const TOPICS: Record<string, string[]> = {
    government: [
        "government", "administration", "regime", "state", "nation", "republic", "commonwealth", "federation", "confederation",
        "executive", "legislature", "judiciary", "parliament", "congress", "senate", "house", "assembly", "council",
        "UN", "NATO", "WTO", "EU", "AU", "ASEAN", "ICC", "BRICS", "municipality", "county", "province", "prefecture", "borough", "township",
        "president", "prime_minister", "chancellor", "monarch", "governor", "mayor", "premier", "dictator", "senator", "representative",
        "congressman", "congresswoman", "ambassador", "diplomat", "secretary", "attorney_general", "treasurer", "commissioner",
        "bureaucrat", "magistrate", "sheriff", "democracy", "autocracy", "oligarchy", "monarchy", "theocracy", "totalitarianism",
        "fascism", "socialism", "communism", "capitalism", "libertarianism", "anarchism", "federalism", "nationalism", "election",
        "vote", "ballot", "referendum", "primary", "caucus", "campaign", "candidate", "electorate", "constituency", "gerrymandering",
        "suffrage", "turnout", "lobbying", "constitution", "law", "statute", "bill", "amendment", "decree", "treaty", "ordinance",
        "regulation", "impeachment", "veto", "judicial_review", "supreme_court", "verdict", "policy", "tax", "budget", "deficit",
        "tariff", "subsidy", "welfare", "infrastructure", "education_policy", "healthcare", "defense", "immigration", "sanctions",
        "citizen", "civil_rights", "sovereignty", "jurisdiction", "federal", "unitary", "autonomy", "separation_of_powers",
        "checks_and_balances", "transparency", "corruption", "diplomacy", "alliance", "embassy", "summit", "foreign_aid",
        "intervention", "espionage", "propaganda", "soft_power", "hard_power", "feudalism", "colonialism", "imperialism",
        "mercantilism", "absolutism", "cabinet", "capital", "civic", "civil_service", "coalition", "delegation", "doctrine",
        "enactment", "franchise", "hegemony", "ideology", "inauguration", "indictment", "injunction", "legitimacy", "mandate",
        "partisan", "plebiscite", "quorum", "ratification", "recession", "redistricting", "repeal", "resolution", "secession",
        "suffrage", "surveillance", "tribunal", "tyranny", "unanimous", "usurpation", "veto_override", "whip", "xenophobia",
        "yardstick", "zionism", "accountability", "adjudication", "amnesty", "annexation", "arbitration", "aristocracy",
        "authoritarianism", "autarky", "bicameral", "bilateral", "boycott", "bureaucracy", "by-election", "cabinet", "caucus",
        "censorship", "centralization", "charter", "citizenship", "coalition", "coercion", "collectivism", "confederation",
        "consensus", "conservatism", "constituent", "convention", "corporatism", "coup", "decentralization", "deficit",
        "delegation", "demagogue", "despotism", "detente", "devolution", "discretion", "dissolution", "divine_right", "docket",
        "dynasty", "egalitarianism", "electoral_college", "elitism", "embargo", "eminent_domain", "entitlement", "envoy",
        "executive_order", "extradition", "faction", "federal_reserve", "filibuster", "fiscal", "foreign_policy", "franchise",
        "free_market", "frontier", "gazette", "gerontocracy", "globalization", "governance", "grand_jury", "grassroots",
        "hegemony", "human_rights", "immunity", "inauguration", "incumbent", "independence", "initiative", "institution",
        "integration", "interregnum", "isolationism", "jingoism", "judicial_activism", "junta", "kingship", "lame_duck",
        "landmark", "left_wing", "legation", "litigation", "lobbyist", "mandamus", "martial_law", "meritocracy", "militarism",
        "minority", "mobilization", "monopoly", "moratorium", "multilateral", "nationalization", "neocolonialism", "nepotism",
        "neutrality", "nomination", "nonpartisan", "nullification", "oligopoly", "opposition", "oversight", "pardon",
        "parliamentarian", "partisanship", "patronage", "peacekeeping", "plenary", "pluralism", "pocket_veto", "polarization",
        "politburo", "poll_tax", "pork_barrel", "precedent", "prerogative", "presidium", "privatization", "proclamation",
        "proportional_representation", "protectorate", "public_opinion", "quango", "quasi_judicial", "question_time",
        "quorum", "rally", "ratification", "realpolitik", "recall", "recession", "recognition", "red_tape", "redistribution",
        "referendum", "reform", "regulation", "repeal", "representation", "republicanism", "resignation", "restraint",
        "retroactivity", "right_wing", "sanctuary", "secularism", "sedition", "self_government", "separation", "sessions",
        "slander", "social_contract", "sovereign", "stalemate", "statism", "subpoena", "subsidy", "suffrage", "summit",
        "superpower", "supranational", "suspension", "tariff", "term_limit", "testimonial", "totalitarian", "town_hall",
        "trade_policy", "treason", "treaty", "tribunal", "trustee", "tyranny", "unicameral", "unilateral", "union", "unitary",
        "urban_policy", "usurpation", "vassal", "veto", "voter_suppression", "war_powers", "welfare_state", "whip",
        "white_paper", "writ", "xenophobia", "yield", "zero_tolerance", "zoning"
    ],
    technology: [
        "computer",
        "software",
        "internet",
        "algorithm",
        "database",
        "network",
        "program",
        "code",
        "hardware",
        "ai",
        "blockchain",
        "cloud",
        "cybersecurity",
        "robotics",
        "data",
        "virtual",
        "quantum",
    ],
    sports: [
        "football",
        "basketball",
        "tennis",
        "stadium",
        "player",
        "coach",
        "team",
        "match",
        "goal",
        "olympics",
        "referee",
        "championship",
        "medal",
        "league",
        "fans",
        "training",
        "athlete",
    ],
    music: [
        "guitar",
        "piano",
        "concert",
        "album",
        "song",
        "lyrics",
        "band",
        "singer",
        "rhythm",
        "melody",
        "chorus",
        "harmony",
        "microphone",
        "genre",
        "composer",
        "orchestra",
        "beat",
    ],
    science: [
        "biology",
        "chemistry",
        "physics",
        "experiment",
        "theory",
        "research",
        "lab",
        "scientist",
        "discovery",
        "microscope",
        "genetics",
        "atom",
        "neutron",
        "quantum",
        "telescope",
        "evolution",
        "molecule",
    ],
    health: [
        "doctor",
        "nurse",
        "hospital",
        "medicine",
        "disease",
        "vaccine",
        "symptom",
        "therapy",
        "nutrition",
        "fitness",
        "mental",
        "infection",
        "diet",
        "recovery",
        "clinic",
        "hygiene",
    ],
    education: [
        "school",
        "teacher",
        "student",
        "university",
        "lesson",
        "homework",
        "exam",
        "curriculum",
        "subject",
        "degree",
        "textbook",
        "classroom",
        "lecture",
        "graduate",
        "scholarship",
        "academic",
    ],
    finance: [
        "money",
        "bank",
        "loan",
        "credit",
        "investment",
        "budget",
        "income",
        "savings",
        "tax",
        "currency",
        "interest",
        "account",
        "economy",
        "debt",
        "stock",
        "profit",
    ],
    environment: [
        "climate",
        "pollution",
        "recycling",
        "energy",
        "conservation",
        "ecosystem",
        "deforestation",
        "greenhouse",
        "carbon",
        "wildlife",
        "nature",
        "global",
        "sustainability",
        "weather",
        "earth",
    ],
};