import { fetch } from "../../utils/fetch.mts";

const AI = {
	/** GROQ AI */
	async groq(prompt: string): Promise<string> {
		const res = await fetch(
			`https://bk9.fun/ai/groq?q=${encodeURIComponent(prompt)}`,
		);
		return JSON.parse(res).BK9 ?? "No response from Groq.";
	},

	/** LLAMA AI */
	async llama(prompt: string): Promise<string> {
		const res = await fetch(
			`https://bk9.fun/ai/llama?q=${encodeURIComponent(prompt)}`,
		);
		return JSON.parse(res).BK9 ?? "No response from LLaMA.";
	},

	/** DALLE Image */
	async dalle(prompt: string): Promise<string> {
		return `https://bk9.fun/ai/magicstudio?prompt=${encodeURIComponent(prompt)}`;
	},

	/** NIKKA AI */
	async nikka(prompt: string): Promise<string> {
		const res = await fetch(
			`https://bk9.fun/ai/nikka?q=${encodeURIComponent(prompt)}`,
		);
		return JSON.parse(res).BK9 ?? "No response from Nikka.";
	},

	/** JEEVS AI */
	async jeevs(prompt: string): Promise<string> {
		const res = await fetch(
			`https://bk9.fun/ai/jeevs?q=${encodeURIComponent(prompt)}`,
		);
		return JSON.parse(res).BK9 ?? "No response from Jeevs.";
	},

	/** MATHS AI */
	async maths(prompt: string): Promise<string> {
		const res = await fetch(
			`https://bk9.fun/ai/maths?q=${encodeURIComponent(prompt)}`,
		);
		return JSON.parse(res).BK9 ?? "No response from Maths.";
	},

	/** FLUX Image Gen */
	async flux(prompt: string): Promise<string> {
		const res = await fetch(
			`https://bk9.fun/ai/flux?q=${encodeURIComponent(prompt)}`,
		);
		return JSON.parse(res).BK9 ?? "No image generated by Flux.";
	},
};

export default AI;
